name: PHP Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, intl, pdo
        tools: composer, phpunit
        coverage: xdebug

    - name: Install Dependencies
      run: composer install

    - name: Make PHPUnit Executable
      run: chmod +x vendor/bin/phpunit

    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --bootstrap vendor/autoload.php tests
